pip install selenium
@echo off
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "__________________________________________________________"
echo "|  please edit username and password in settings.txt file |"
echo "|                                                         |"
echo "|   you can close this window then and run ASVZBot.bat    |"
echo "|_________________________________________________________|"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
@echo off
pause
